import os
from dotenv import load_dotenv

load_dotenv()

ENCODER_MODEL_ID = os.getenv('ENCODER_MODEL_ID')

HARDWARE_TYPE_CLASSIFIER_PATH = os.getenv('HARDWARE_TYPE_CLASSIFIER_PATH')
REQUEST_TYPE_CLASSIFIER_PATH = os.getenv('REQUEST_TYPE_CLASSIFIER_PATH')

DATASET = os.getenv('DATASET')
HARDWARE_TYPE_DATASET = os.getenv('HARDWARE_TYPE_DATASET')
REQUEST_TYPE_DATASET = os.getenv('REQUEST_TYPE_DATASET')

DB_URL = os.getenv('DB_URL')
